---
- name: Install Wordpress, MySQL, Nginx, PHP-FPM, and vsftpd
  hosts: all
  # user: root
  user: vagrant
  sudo: true

  roles:
    - common
    - ufw
    - mysql
    - memcached
    - nginx
    - php-fpm
    - wordpress
    - ftp
