---
- name: Install Wordpress, MySQL, Nginx, and PHP-FPM
  hosts: all
  # user: root
  user: vagrant
  sudo: true

  roles:
    - common
    - mysql
    - memcached
    - nginx
    - php-fpm
    - wordpress
