---
- name: Download Wordpress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/var/www/wordpress-{{ wp_version }}.tar.gz
           sha256sum="{{ wp_sha256sum }}"

- name: Extract archive
  command: chdir=/var/www/ /bin/tar xvf wordpress-{{ wp_version }}.tar.gz creates={{ wp_home }}

- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home={{ wp_home }}/

- name: Change ownership of Wordpress installation
  file: path={{ wp_home }}/ owner=wordpress group=wordpress state=directory recurse=yes

- name: Fetch random salts for Wordpress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: wp_salt
  sudo: false

- name: Create Wordpress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create Wordpress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present

- name: Copy Wordpress config file
  template: src=wp-config.php dest={{ wp_home }}/ force=false

# - name: Install advanced-cache.php from Automattic's github repo
#   get_url: url=https://raw.github.com/Automattic/batcache/master/advanced-cache.php dest={{ wp_home }}/wp-content/advanced-cache.php
#
# - name: Install batcache from Automattic's github repo
#   get_url: url=https://raw.github.com/Automattic/batcache/master/batcache.php dest={{ wp_home }}/wp-content/batcache.php
#
# - name: Pull theme code from Github
#   git: repo=https://github.com/dailyemerald/EMG-Wordpress-Theme.git dest={{ wp_home }}/wp-content/themes/emg-theme
#   notify:
#   - restart php5-fpm
