---
- name: Install necessities and nice-to-haves
  apt: pkg=$item state=installed
  with_items:
    - sudo
    - vim
    - htop
    - iftop
    - iotop
    - mosh
    - zsh
    - git
    - encfs
    - libfuse-dev
    - fuse-utils
    - ruby1.9.3
    - screen
    - tmux
    - build-essential
    - apticron
    - update-notifier-common
    - debian-goodies
